blank_issues_enabled: false
contact_links:
  - name: CometCord Support Server
    url: https://discord.gg/D9uwnFnqmd
    about: If you need help regarding CometCord, please join our support server!
  - name: CometCord Installer
    url: https://github.com/CometCord/Installer
    about: You can find the CometCord Installer here
